### ISSUE TITLE
vLLM: 模型权重转换保存路径逻辑有点问题

### ISSUE THREAD

**Issue by wangkang-mt** [MooreThreads/tutorial_on_musa#14]
原模型路径在/workspace/Qwen2.5-0.5B-Instruct
自动保存路径: /workspace_convert/Qwen2.5-0.5B-Instruct-tp1-convert

**Comment by gliangMT** [comment]
这里为了方便快速，convert_weight脚本逻辑是在将path/{ORIN_MODEL}的原始模型进行转换，转换后模型存到path_convert/{CONVERT_MODEL}
